apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: SealedSecretController.v1alpha1.bitnami.com
  generateName: sealed-secrets-
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  targetNamespaces:
    - sealed-secrets